In [41]:
import pandas as pd
import polars as pl

# Чтение данных

In [47]:
df_pandas = pd.read_csv('data/freelancer_earnings_bd.csv',)

In [48]:
df_pandas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1950 entries, 0 to 1949
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Freelancer_ID      1950 non-null   int64
 1   Job_Category       1950 non-null   object
 2   Platform           1950 non-null   object
 3   Experience_Level   1950 non-null   object
 4   Client_Region      1950 non-null   object
 5   Payment_Method     1950 non-null   object
 6   Job_Completed      1950 non-null   int64
 7   Earnings_USD       1950 non-null   int64
 8   Hourly_Rate        1950 non-null   float64
 9   Job_Success_Rate   1950 non-null   float64
 10  Client_Rating      1950 non-null   float64
 11  Job_Duration_Days  1950 non-null   int64
 12  Project_Type       1950 non-null   object
 13  Rehire_Rate        1950 non-null   float64
 14  Marketing_Spend    1950 non-null   int64
dtypes: float64(4), int64(5), object(6)
memory usage: 228.6+ KB

In [51]:
df_pandas

,Freelancer_ID,Job_Category,Platform,Experience_Level,Client_Region,Payment_Method,Job_Completed,Earnings_USD,Hourly_Rate,Job_Success_Rate,Client_Rating,Job_Duration_Days,Project_Type,Rehire_Rate,Marketing_Spend
0,1,Web Development,Fiverr,Beginner,Asia,Mobile Banking,180,1620,95.79,68.73,3.18,1,Fixed,40.19,53
1,2,App Development,Fiverr,Beginner,Australia,Mobile Banking,218,9078,86.38,97.54,3.44,54,Fixed,36.53,486
2,3,Web Development,Fiverr,Beginner,UK,Crypto,27,3455,85.17,86.60,4.20,46,Hourly,74.05,489
3,4,Data Entry,PeoplePerHour,Intermediate,Asia,Bank Transfer,17,5577,14.37,79.93,4.47,41,Hourly,27.58,67
4,5,Digital Marketing,Upwork,Expert,Asia,Crypto,245,5898,99.37,57.80,5.00,41,Hourly,69.09,489
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1945,1946,Graphic Design,Fiverr,Beginner,USA,Mobile Banking,143,6823,22.54,75.86,4.65,13,Hourly,26.55,133
1946,1947,SEO,Upwork,Intermediate,Middle East,Crypto,164,7942,77.20,72.01,3.29,34,Hourly,24.81,343
1947,1948,SEO,PeoplePerHour,Expert,UK,Bank Transfer,236,9838,24.64,57.37,4.67,38,Fixed,61.52,370
1948,1949,SEO,Freelancer,Intermediate,Europe,Bank Transfer,152,4492,71.07,66.41,4.08,70,Fixed,32.40,32
1949,1950,Graphic Design,Freelancer,Expert,Middle East,PayPal,247,9297,22.22,71.70,4.69,68,Fixed,45.42,236

# Запрос к LLM

In [ ]:
# %pip install openai
# %pip install polars

In [ ]:
import io

df_decribe = io.StringIO()
df_pandas.info(buf=df_decribe)
info = df_decribe.getvalue()
print(info)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1950 entries, 0 to 1949
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Freelancer_ID      1950 non-null   int64
 1   Job_Category       1950 non-null   object
 2   Platform           1950 non-null   object
 3   Experience_Level   1950 non-null   object
 4   Client_Region      1950 non-null   object
 5   Payment_Method     1950 non-null   object
 6   Job_Completed      1950 non-null   int64
 7   Earnings_USD       1950 non-null   int64
 8   Hourly_Rate        1950 non-null   float64
 9   Job_Success_Rate   1950 non-null   float64
 10  Client_Rating      1950 non-null   float64
 11  Job_Duration_Days  1950 non-null   int64
 12  Project_Type       1950 non-null   object
 13  Rehire_Rate        1950 non-null   float64
 14  Marketing_Spend    1950 non-null   int64
dtypes: float64(4), int64(5), object(6)
memory usage: 228.6+ KB

In [ ]:
request_finance_1 = "Насколько выше доход у фрилансеров, принимающих оплату в криптовалюте, по сравнению с другими способами оплаты?"
request_finance_2 = "Как распределяется доход фрилансеров в зависимости от региона проживания?"
request_finanse_3 = "Какой процент фрилансеров, считающих себя экспертами, выполнил менее 100 проектов?"

prompt = f"""У тебя есть следующее описание датафрейма Pandas с данными "{info}". 
Также у тебя есть следующий запрос пользователя на естественном языке:
"{request_finanse_3}".

Выведи запрос, который я можно передать в метод query библиотеки pandas, чтобы получить все строки датафрейма,  
удовлетворяющие условию, которое ввел пользователь. Ответ должен быть в формате: df.query('Earnings_USD > 1000')""" 

prompt_python = f"""У тебя есть следующее описание датафрейма Pandas с данными "{info}". 
Также у тебя есть следующий запрос пользователя на естественном языке:
"{request_finance_2}".

Выведи код на Python, выполнив который, я смогу получить ответ на запрос пользователя. Этот код не должен содержать никаких графических библиотек. 
Результат выполнения этого кода должен выводиться только в консоль""" 

prompt_polars = f"""У тебя есть следующее описание датафрейма Pandas с данными "{info}". 
Также у тебя есть следующий запрос пользователя на естественном языке:
"{request_finance_1}".

Выведи запрос на SQL, который можно передать в метод `sql` библиотеки polars, чтобы получить ответ на запрос пользователя.
Выведи ТОЛЬКО код на SQL, без каких-либо пояснений."""

In [ ]:
from openai import OpenAI

client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key="<OPENROUTER_API_KEY>",
)

completion = client.chat.completions.create(
  extra_headers={
  },
  extra_body={},
  model="qwen/qwen3-32b:free",
  messages=[
    {
      "role": "user",
      "content": prompt_polars
    }
  ],
  temperature=0.0,
)

print(completion.choices[0].message.content)

In [42]:
df = pl.read_csv('data/freelancer_earnings_bd.csv')

In [58]:
pl.sql('SELECT Client_Region, SUM(Earnings_USD) FROM df GROUP BY Client_Region').collect()

shape: (7, 2)
┌───────────────┬──────────────┐
│ Client_Region ┆ Earnings_USD │
│ ---           ┆ ---          │
│ str           ┆ i64          │
╞═══════════════╪══════════════╡
│ Canada        ┆ 1316133      │
│ Asia          ┆ 1453412      │
│ Europe        ┆ 1281319      │
│ Australia     ┆ 1479897      │
│ Middle East   ┆ 1417408      │
│ UK            ┆ 1413185      │
│ USA           ┆ 1422901      │
└───────────────┴──────────────┘

In [57]:
pl.sql("SELECT ROUND((COUNT(CASE WHEN Experience_Level = 'Expert' AND Job_Completed < 100 THEN 1 END) * 100.0 / COUNT(CASE WHEN Experience_Level = 'Expert' THEN 1 END)), 2) AS percentage FROM df WHERE Experience_Level = 'Expert'").collect()

shape: (1, 1)
┌────────────┐
│ percentage │
│ ---        │
│ f64        │
╞════════════╡
│ 33.85      │
└────────────┘